
<div class="header-spacer"></div>

<!-- ... End Header -->

<div class="content-wrapper">

	<!-- Stunning-header -->

	<div class="stunning-header stunning-header-bg-breez2">
		<div class="stunning-header-content">
			<h1 class="stunning-header-title1">Mechanical Trades</h1>
			<ul class="breadcrumbs">
				<li class="breadcrumb-item">
					<a href="<?=base_url()?>">Home</a>
					<i class="seoicon-right-arrow"></i>
				</li>
				<li class="breadcrumb-item active">
					<span>Mechanical Trades</span>
					
				</li>
			</ul>
		</div>
	</div>

	<!-- End Stunning-header -->

	<!-- Overlay Search -->

	<div class="overlay_search">
		<div class="container">
			<div class="row">
				<div class="form_search-wrap">
					<form>
						<input class="overlay_search-input" placeholder="Type and hit Enter..." type="text">
						<a href="#" class="overlay_search-close">
							<span></span>
							<span></span>
						</a>
					</form>
				</div>
			</div>
		</div>
	</div>

	<!-- End Overlay Search -->

	<div class="container-fluid">
		<div class="row pt120">
			<div class="container">
				<div class="row">
					<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
						<div class="heading align-center pb120">
							<h4 class="h1 heading-title">Mechanical Trades Contractors Love additional profits, generated by Pnapna</h4>
							<div class="heading-line">
								<span class="short-line"></span>
								<span class="long-line"></span>
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="local-seo">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<img src="<?=base_url()?>assets/biz/img/local-seo1.jpg" alt="local-seo">
							<img src="<?=base_url()?>assets/biz/img/local-seo2.jpg" alt="local-seo">
							<img src="<?=base_url()?>assets/biz/img/local-seo-main.jpg" alt="local-seo" class="shadow-image">
						</div>
					</div>
				</div>

			</div>
		</div>

		<div class="row medium-padding120 bg-border-color">
			<div class="container">

				<div class="row align-center">

					<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
						<div class="h5 c-gray pt100">Mechanical trades are getting harder to compete every day.  You need to get organized and watch every penny not fall through the cracks. Pnapna helps you do that. From automatic emailing, reliable data for bidding and more.
						</div>

						<div class="btn btn-medium btn--blue btn-hover-shadow mt60">
							<span class="text">Tell Us About Your Project</span>
							<span class="semicircle"></span>
						</div>

					</div>

				</div>
			</div>
		</div>
	</div>

     <div class="container-fluid">
		<div class="row pt120">
			<div class="container">
				<div class="row">
					<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
						<div class="heading align-center pb100">
							<h4 class="h1 heading-title">Mechanical Trades We Serve</h4>
							<div class="heading-line">
								<span class="short-line"></span>
								<span class="long-line"></span>
							</div>
						</div>
					</div>
				</div>

				

			</div>
		</div>
	</div>
	</div>
	
	
	<div class="container">
		<div class="row pb100">

			<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb30" style="line-height: 3">
			
				<h4 class="info-box-title text-t-none"><img src="<?=base_url()?>assets/biz/img/Commercial-Kitchens.png" > &nbsp  Commercial Kitchens</h4>
				<h4 class="info-box-title text-t-none"> <img src="<?=base_url()?>assets/biz/img/sever.png"> &nbsp Drain And Sewer Cleaning</h4>
				<h4 class="info-box-title text-t-none"> <img src="<?=base_url()?>assets/biz/img/Electrical.png"> &nbsp Electrical</h4>
				<h4 class="info-box-title text-t-none"> <img src="<?=base_url()?>assets/biz/img/Escalators.png"> &nbsp Elevators And Escalators</h4>
				<h4 class="info-box-title text-t-none"> <img src="<?=base_url()?>assets/biz/img/Erection.png"> &nbsp Erection</h4>
					<h4 class="info-box-title text-t-none"> <img src="<?=base_url()?>assets/biz/img/HVAC.png">&nbsp  HVAC</h4>
				
			</div>

			<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12"style="line-height: 3">
				<div class="heading">
 
					
    		
				<h4 class="info-box-title text-t-none"> <img src="<?=base_url()?>assets/biz/img/Underground-Tanks.png"> &nbsp Oil And Underground Tanks</h4>
				<h4 class="info-box-title text-t-none"> <img src="<?=base_url()?>assets/biz/img/plumbing.png"> &nbsp Plumbing</h4>
				<h4 class="info-box-title text-t-none"> <img src="<?=base_url()?>assets/biz/img/Pipe-Fitting.png"> &nbsp Pipe Fitting</h4>
				<h4 class="info-box-title text-t-none"> <img src="<?=base_url()?>assets/biz/img/Sprinkler.png"> &nbsp Sprinkler</h4>
				<h4 class="info-box-title text-t-none"> <img src="<?=base_url()?>assets/biz/img/Steel-Erection.png">&nbsp  Steel Erection</h4>
				<h4 class="info-box-title text-t-none"> <img src="<?=base_url()?>assets/biz/img/Septic.png">&nbsp  Septic</h4>
    		
    	</div>

				
			</div>

		</div>
	</div>
    
	
	<div class="container-fluid">
		<div class="row medium-padding120 bg-orange-color">
			<div class="container">
				<div class="row mb30">
					<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
						<div class="heading align-center">
							<h4 class="h1 heading-title">Pnapna Is The First Tool You Need</h4>
							<div class="heading-line">
								<span class="short-line bg-yellow-color"></span>
								<span class="long-line bg-yellow-color"></span>
							</div>
							<p class="heading-text c-white">To start or grow your business for it toi be most profitable.</p>
						</div>

					</div>

				</div>

				<div class="row">
					<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">

						<div class="info-box--standard">
							<div class="info-box-image">
								<img src="<?=base_url()?>assets/biz/img/info-box23.png" alt="image">
							</div>
							<div class="info-box-content">
								<h5 class="info-box-title">Free Leads From Marketplace</h5>
								<p class="text c-white">All contractors get a free listing for life for your trade in the zip code where you operate. All leads are imported in to the system 24/7/365 accomatically, even when you are away. 
								</p>
							</div>
						</div>

					</div>

					<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">

						<div class="info-box--standard">
							<div class="info-box-image">
								<img src="<?=base_url()?>assets/biz/img/info-box24.png" alt="image">
							</div>
							<div class="info-box-content">
								<h5 class="info-box-title">Order Forms In Website </h5>
								<p class="text c-white">We can install the Order Form Widget in any website, from any outside website builder or ours. The widgets are higly customizable and can be used for payments too. 
								</p>
							</div>
						</div>

					</div>

				</div>
			</div>
		</div>
	</div>



	<div class="container">
		<div class="row pt120">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="heading">
					<h4 class="h1 heading-title">Let Us Help You Make Money</h4>
					<div class="heading-line">
						<span class="short-line"></span>
						<span class="long-line"></span>
					</div>

					<p>Let us help you get your business online and grow it with passion.
					</p>
				</div>
			</div>
		</div>

		<div class="row pb120">

			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div>
					<form class="contact-form" method="post" action="send_mail.php">
						<div class="row">

							<div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
								<div class="row">
									<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
										<input name="permalink" class="email input-standard-grey" placeholder="Website URL" type="url">
									</div>
								</div>

								<div class="row">
									<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
										<input name="name" class="email input-standard-grey" required placeholder="Your Name" type="text">
									</div>
									<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
										<input name="phone" class="email input-standard-grey" placeholder="Phone" type="text">
									</div>
								</div>

								<div class="row">
									<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
										<input name="email" class="email input-standard-grey" required placeholder="Email Address" type="email">
									</div>
									<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
										<input name="company" class="email input-standard-grey" placeholder="Company" type="text">
									</div>
								</div>
							</div>

							<div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
								<textarea name="message" class="email input-standard-grey" required placeholder="Details" style="height: 250px;"></textarea>
							</div>
						</div>
						<div class="row">
							<div class="submit-block table">
								<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 table-cell">
									<button class="btn btn-medium btn--breez btn-hover-shadow">
										<span class="text">Send Inquiry</span>
										<span class="semicircle"></span>
									</button>
								</div>
								<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 table-cell">
									<div class="submit-block-text">
										Please, let us know any particular things to check and the best time
										to contact you by phone (if provided).
									</div>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

	<!-- End Contact Form -->

	
</div>